"""Unit tests for the deterministic run-worker context pack (PR-C)."""

from __future__ import annotations

from pathlib import Path
import subprocess

import pytest

from ouroboros.core.seed import (
    BrownfieldContext,
    ContextReference,
    EvaluationPrinciple,
    ExitCondition,
    OntologyField,
    OntologySchema,
    Seed,
    SeedMetadata,
)
from ouroboros.orchestrator.context_pack import (
    MAX_PACK_CHARS,
    ContextPack,
    build_context_pack,
    detected_verify_commands,
    render_context_pack,
)
from ouroboros.orchestrator.runner import build_system_prompt

_PYPROJECT = """\
[project]
name = "fixture-app"
version = "1.2.3"
requires-python = ">=3.12"
dependencies = ["pytest", "ruff"]
"""

# Top-level command keys, matching the detector's persisted format read by
# ``build_mechanical_config`` -> ``_apply_overrides``. Commands are declared by
# the fixture pyproject so the detector's entry-point validator accepts them.
_MECHANICAL_TOML = """\
# auto-generated by ouroboros evaluate detector
test = "uv run pytest"
lint = "ruff check ."
"""


def _write_fixture_repo(root: Path) -> None:
    (root / "pyproject.toml").write_text(_PYPROJECT, encoding="utf-8")
    ouroboros_dir = root / ".ouroboros"
    ouroboros_dir.mkdir(parents=True, exist_ok=True)
    (ouroboros_dir / "mechanical.toml").write_text(_MECHANICAL_TOML, encoding="utf-8")
    src = root / "src"
    src.mkdir()
    (src / "main.py").write_text("print('hi')\n", encoding="utf-8")
    (root / "tests").mkdir()


def _sample_seed(brownfield: BrownfieldContext | None = None) -> Seed:
    return Seed(
        goal="Build a task management CLI",
        brownfield_context=brownfield or BrownfieldContext(),
        constraints=("No external database",),
        acceptance_criteria=("Tasks can be created",),
        ontology_schema=OntologySchema(
            name="TaskManager",
            description="Task management ontology",
            fields=(OntologyField(name="tasks", field_type="array", description="Tasks"),),
        ),
        evaluation_principles=(
            EvaluationPrinciple(name="completeness", description="All requirements are met"),
        ),
        exit_conditions=(
            ExitCondition(
                name="done",
                description="All acceptance criteria satisfied",
                evaluation_criteria="pass",
            ),
        ),
        metadata=SeedMetadata(ambiguity_score=0.15),
    )


class TestScanner:
    def test_pack_from_fixture_repo(self, tmp_path: Path) -> None:
        _write_fixture_repo(tmp_path)
        pack = build_context_pack(tmp_path)
        assert pack is not None
        assert any("fixture-app 1.2.3" in line for line in pack.stack)
        assert any(line.startswith("test:") and "pytest" in line for line in pack.verify_commands)
        rendered = render_context_pack(pack)
        assert "## Project Context (auto-detected facts)" in rendered
        assert "fixture-app" in rendered
        assert "uv run pytest" in rendered
        # Layout surfaces the top-level directories.
        assert "src/" in rendered

    def test_empty_dir_yields_no_pack(self, tmp_path: Path) -> None:
        assert build_context_pack(tmp_path) is None

    def test_nonexistent_path_yields_no_pack(self, tmp_path: Path) -> None:
        assert build_context_pack(tmp_path / "does-not-exist") is None

    def test_file_path_yields_no_pack(self, tmp_path: Path) -> None:
        f = tmp_path / "a.txt"
        f.write_text("x", encoding="utf-8")
        assert build_context_pack(f) is None

    def test_verify_commands_empty_without_toml(self, tmp_path: Path) -> None:
        (tmp_path / "pyproject.toml").write_text(_PYPROJECT, encoding="utf-8")
        assert detected_verify_commands(tmp_path) == ()

    def test_stack_only_still_produces_pack(self, tmp_path: Path) -> None:
        # A manifest with no mechanical.toml is enough (stack is a real fact).
        (tmp_path / "pyproject.toml").write_text(_PYPROJECT, encoding="utf-8")
        pack = build_context_pack(tmp_path)
        assert pack is not None
        assert pack.verify_commands == ()
        assert pack.stack


class TestBudget:
    def test_render_truncates_repo_map_first(self) -> None:
        huge_map = tuple(f"  dir_{i}_{'x' * 80}/" for i in range(500))
        pack = ContextPack(
            stack=("Python (pyproject): fixture-app 1.2.3",),
            verify_commands=("test: uv run pytest",),
            repo_map=huge_map,
        )
        rendered = render_context_pack(pack)
        assert len(rendered) <= MAX_PACK_CHARS
        # Stack + verify facts survive truncation.
        assert "fixture-app 1.2.3" in rendered
        assert "uv run pytest" in rendered


class TestCache:
    def _init_git(self, root: Path) -> None:
        subprocess.run(["git", "init", "-q"], cwd=root, check=True)
        subprocess.run(["git", "add", "-A"], cwd=root, check=True)
        subprocess.run(
            ["git", "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", "init"],
            cwd=root,
            check=True,
        )

    def test_cache_written_and_hit(self, tmp_path: Path) -> None:
        _write_fixture_repo(tmp_path)
        self._init_git(tmp_path)
        first = build_context_pack(tmp_path)
        assert first is not None
        cache_path = tmp_path / ".ouroboros" / "context_pack.json"
        assert cache_path.is_file()

        # Rewrite the cache with a sentinel stack but the same HEAD → a hit
        # must return the sentinel, proving the scan was skipped.
        import json

        data = json.loads(cache_path.read_text(encoding="utf-8"))
        data["stack"] = ["SENTINEL cached stack"]
        cache_path.write_text(json.dumps(data), encoding="utf-8")
        cached = build_context_pack(tmp_path)
        assert cached is not None
        assert cached.stack == ("SENTINEL cached stack",)

    def test_cache_miss_on_head_change(self, tmp_path: Path) -> None:
        _write_fixture_repo(tmp_path)
        self._init_git(tmp_path)
        build_context_pack(tmp_path)
        cache_path = tmp_path / ".ouroboros" / "context_pack.json"

        import json

        data = json.loads(cache_path.read_text(encoding="utf-8"))
        data["stack"] = ["SENTINEL cached stack"]
        cache_path.write_text(json.dumps(data), encoding="utf-8")

        # New commit → HEAD changes → the sentinel cache is stale and rescanned.
        (tmp_path / "extra.py").write_text("x = 1\n", encoding="utf-8")
        subprocess.run(["git", "add", "-A"], cwd=tmp_path, check=True)
        subprocess.run(
            ["git", "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", "second"],
            cwd=tmp_path,
            check=True,
        )
        fresh = build_context_pack(tmp_path)
        assert fresh is not None
        assert fresh.stack != ("SENTINEL cached stack",)
        assert any("fixture-app" in line for line in fresh.stack)

    def test_cache_miss_on_working_tree_source_change(self, tmp_path: Path) -> None:
        """Editing a parsed source with HEAD fixed must invalidate the cache.

        Regression for the HEAD-only cache key: the pack is built from mutable
        working-tree files, so a pyproject.toml edit without a commit used to
        keep serving the stale cached pack.
        """
        _write_fixture_repo(tmp_path)
        self._init_git(tmp_path)
        first = build_context_pack(tmp_path)
        assert first is not None
        assert any("fixture-app 1.2.3" in line for line in first.stack)

        # Same HEAD, new working-tree manifest content → fresh pack, not cache.
        (tmp_path / "pyproject.toml").write_text(
            _PYPROJECT.replace('version = "1.2.3"', 'version = "9.9.9"'),
            encoding="utf-8",
        )
        fresh = build_context_pack(tmp_path)
        assert fresh is not None
        assert any("fixture-app 9.9.9" in line for line in fresh.stack)
        assert not any("1.2.3" in line for line in fresh.stack)

    def test_non_git_dir_scans_without_cache(self, tmp_path: Path) -> None:
        _write_fixture_repo(tmp_path)
        pack = build_context_pack(tmp_path)
        assert pack is not None
        assert pack.head is None
        assert not (tmp_path / ".ouroboros" / "context_pack.json").is_file()


class TestSystemPromptInjection:
    def test_pack_present_when_flag_on(self, tmp_path: Path, monkeypatch) -> None:
        monkeypatch.setenv("OUROBOROS_CONTEXT_PACK", "1")
        _write_fixture_repo(tmp_path)
        prompt = build_system_prompt(_sample_seed(), repo_root=tmp_path)
        assert "## Project Context (auto-detected facts)" in prompt
        assert "fixture-app" in prompt

    def test_pack_absent_when_flag_off(self, tmp_path: Path, monkeypatch) -> None:
        monkeypatch.setenv("OUROBOROS_CONTEXT_PACK", "0")
        _write_fixture_repo(tmp_path)
        prompt = build_system_prompt(_sample_seed(), repo_root=tmp_path)
        assert "## Project Context (auto-detected facts)" not in prompt

    def test_pack_absent_for_empty_dir(self, tmp_path: Path, monkeypatch) -> None:
        monkeypatch.setenv("OUROBOROS_CONTEXT_PACK", "1")
        prompt = build_system_prompt(_sample_seed(), repo_root=tmp_path)
        assert "## Project Context (auto-detected facts)" not in prompt

    def test_pack_absent_without_repo_root(self, monkeypatch) -> None:
        monkeypatch.setenv("OUROBOROS_CONTEXT_PACK", "1")
        prompt = build_system_prompt(_sample_seed())
        assert "## Project Context (auto-detected facts)" not in prompt

    def test_root_falls_back_to_context_reference(self, tmp_path: Path, monkeypatch) -> None:
        monkeypatch.setenv("OUROBOROS_CONTEXT_PACK", "1")
        _write_fixture_repo(tmp_path)
        brownfield = BrownfieldContext(
            project_type="brownfield",
            context_references=(ContextReference(path=str(tmp_path), role="primary", summary=""),),
        )
        prompt = build_system_prompt(_sample_seed(brownfield), repo_root=None)
        assert "## Project Context (auto-detected facts)" in prompt
        assert "fixture-app" in prompt


@pytest.mark.parametrize(
    "manifest,content,needle",
    [
        ("go.mod", "module example.com/app\n\ngo 1.22\n", "example.com/app"),
        (
            "package.json",
            '{"name": "web", "version": "0.1.0"}',
            "web 0.1.0",
        ),
    ],
)
def test_other_language_stacks(tmp_path: Path, manifest: str, content: str, needle: str) -> None:
    (tmp_path / manifest).write_text(content, encoding="utf-8")
    pack = build_context_pack(tmp_path)
    assert pack is not None
    assert any(needle in line for line in pack.stack)
